"""
kite_client.py – Factory for authenticated KiteConnect instances.

Reads credentials exclusively from environment variables so that no secrets
are embedded in application code.

Required environment variables
--------------------------------
KITE_API_KEY        – Zerodha API key (required at runtime).
KITE_ACCESS_TOKEN   – Session access token (required; generated by the login
                      flow in ``kite_tools.KiteAuthManager``).

Optional
--------
KITE_USER_ID        – Zerodha user-id (used by automated TOTP login).
"""

from __future__ import annotations

import os
from typing import Any

from dotenv import load_dotenv
from loguru import logger

load_dotenv()

# Optional import so the module is importable in tests without kiteconnect.
try:
    from kiteconnect import KiteConnect  # type: ignore
except ImportError:  # pragma: no cover
    KiteConnect = None  # type: ignore


def build_kite_client(
    api_key: str | None = None,
    access_token: str | None = None,
) -> Any:
    """Return an authenticated :class:`kiteconnect.KiteConnect` instance.

    Credentials are resolved in the following priority order:

    1. The *api_key* / *access_token* arguments (useful for testing).
    2. The ``KITE_API_KEY`` / ``KITE_ACCESS_TOKEN`` environment variables.

    Args:
        api_key: Zerodha API key.  Falls back to ``KITE_API_KEY`` env var.
        access_token: Session access token.  Falls back to
            ``KITE_ACCESS_TOKEN`` env var.

    Returns:
        An authenticated ``KiteConnect`` object ready for data calls.

    Raises:
        RuntimeError: If ``kiteconnect`` is not installed.
        KeyError: If ``KITE_API_KEY`` is not set.
        ValueError: If ``KITE_ACCESS_TOKEN`` is not set.
    """
    if KiteConnect is None:
        raise RuntimeError(
            "kiteconnect package is not installed. Run: pip install kiteconnect"
        )

    resolved_key = api_key or os.environ["KITE_API_KEY"]
    resolved_token = access_token or os.environ.get("KITE_ACCESS_TOKEN", "").strip()

    if not resolved_token:
        raise ValueError(
            "KITE_ACCESS_TOKEN is not set. "
            "Run the login flow (KiteAuthManager.get_kite_session) first."
        )

    kite = KiteConnect(api_key=resolved_key)
    kite.set_access_token(resolved_token)
    logger.debug("KiteConnect client ready (api_key={}).", resolved_key[:4] + "****")
    return kite
